### ISSUE TITLE
Haskell-like Range Syntax

### ISSUE THREAD

**Issue by joaolucasl** [quack/quack#23]
As far as I know, currently the range syntax is **`from 1 to n`**. This syntax although highly legible may higher the verbosity of code blocks, as seen in the current imperative factorial example:

``` ocaml

-: imperative
fn fact [n]
  let fact :- 1
  for i from 1 to n do fact :- fact * i
  ^ fact
end

```

Thus, I think it would be benefitial for the language to have a Haskell-like range syntax:

``` haskell
[first..]
[first,second..]
[first..last]
[first,second..last]
```

Thus, a for loop would become: `for i from [1...n]` or `for i in`[1...n] `. 
A point to be noted, though, is how the language would deal with the ranges, since Haskell's lazy eval nature provides itself the ability to deal with 'infinite' ranges.

Alternatively, a Scala-like syntax could be also applicable: `for i <-  1..n` or `for i <- 1 to n` or based on Ruby's `for i in (1..n)`

This is just an idea, haven't put much thought on it.

**Comment by haskellcamargo** [comment]
Well, currently, it is also **valid** to do:

``` python
foreach n in range[ 1; 10 ]
  do print n
end
```

To remove verbosity questions, we could use a range syntax based in `..`:

``` python
foreach n in 1 .. 10
  do print n
end
```

I'm also aiming to implement the following, using list comprehensions:

``` erlang
let even :- :{ x; x <- 1 .. 10; x mod 2 = 0 }
```

For ranges based in steps, we'd need to define an unambiguous syntax. I'm thinking in extend the `..` operator to be **multifix**: `1 .. 10 by 2`. This would _auto-complement_ the `foreach` syntax:

``` python
foreach x in 1 .. 100 by 2 do print x end
```

About the behavior, lazy evaluation could be implemented using coroutines, and it would be a semantic (instead of a syntactic) implementation. It is easily applicable for generation, but every function should be prepared for that. I believe it'll give a nice discussion later, but, at once, lists are evaluated eagerly.

The proposed features are, therefore:
- `<expr> .. <expr> [ by <expr> ]` syntax
- List-comprehension syntax _(discussion opened about, some version)_
