### ISSUE TITLE
BreakStmt and ContinueStmt are not optional in Quack

### ISSUE THREAD

**Issue by luizperes** [quack/quack#78]
The `BreakStmt` and `ContinueStmt` are requiring labels in order to be used.

I think that this error might be occurring [here](https://github.com/quack/quack/blob/master/src/ast/stmt/BreakStmt.php#L56) and [here](https://github.com/quack/quack/blob/master/src/ast/stmt/ContinueStmt.php#L55)

![screen shot 2016-10-07 at 4 34 28 pm](https://cloud.githubusercontent.com/assets/6173065/19208196/1a2334cc-8cac-11e6-87dc-08aa1a4fadbc.png)

Moreover, wouldn't it be a `TypeCheckerError` rather than a `ScopeError`? I think that this block of code should be moved to the `runTypeChecker` method. I also think that the ScopeError should be renamed to `SemanticError` or something similar, as we are not only using it for scope errors.

**Comment by haskellcamargo** [comment]
Well, I've rechecked and they are obligatory because they have different behaviors in languagens like PHP or JS. In PHP, you use numbers to declare how much loops to break. In JS, you use labels instead. By using labels, we'll translate'em to numbers on code generation.

`ScopeError` **must** be removed from _typechecking_. We need to create a `TypeError` class for that. This is _TODO_. If you want to, feel free! :smile:

**Comment by luizperes** [comment]
@haskellcamargo, I think that labels don't have the necessity to be obligatory. For that, we can create  anonymous labels in case that the user does not tell them explicitly. In this case, labels would keep being obligatory in `Quack` for the cases that you mentioned, however that would be optional to the user. What do you think?

I can take that task!

**Comment by luizperes** [comment]
Closing this issue as it has been solved on https://github.com/quack/quack/pull/85
