### ISSUE TITLE
Use PSR-2 standard

### ISSUE THREAD

**Issue by haskellcamargo** [quack/quack#9]
We need to adapt all the source to use the [PSR-2 coding style standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md). It may be harder than expected because some dependencies are not clearly and are in multiple files, but we can do it. The compilers modules are separated in folders under `/src` and we can get one by one.

**Comment by haskellcamargo** [comment]
@sergiors, @marabesi  what about this?

**Comment by gabrielrcouto** [comment]
@haskellcamargo: You can use this tool -> https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by reisraff** [comment]
@haskellcamargo other option is to use it ~> https://github.com/squizlabs/PHP_CodeSniffer/blob/master/scripts/phpcbf

**Comment by haskellcamargo** [comment]
We should note that, if we use a tool that converts the code to the PSR-2 coding style, we need to check the source for some references for named methods, such as [this example](https://github.com/quack/quack/blob/master/src/parser/Grammar.php#L129) does. We have the productions of the grammar referenced as strings, in a branch table.

**Comment by iagocaldeira** [comment]
Couldn't you just run a PHPCodeSniffer tool, and make a step by step correction?
First we could list all files and occurrences and submit as a detailled issue as a checklist :)

**Comment by luizperes** [comment]
I'll take it :)

**Comment by luizperes** [comment]
Most of it is solved here https://github.com/quack/quack/pull/34

**Comment by joaolucasl** [comment]
Thanks @luizperes for getting on top of that!
For the sake of organisation, though, I think it should be clearly defined by this project the preferred style on method and property naming. 
As per the [PSR2 Method Section](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods), I couldn't find a definition on whether we should use 'CamelCase' or 'lower_under', but since [it inherits ](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#21-basic-coding-standard) rules from PSR-1, and the latter does [state the need of camelCase](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview), this may be a point up to discussion, before we merge the PR.

@haskellcamargo, thoughts on this?

**Comment by haskellcamargo** [comment]
Currently, the pattern looks **OK**. After, but within another task, we can verify the naming issues provided by _CodeClimate_. :smile:
